# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2015 Mateusz Kulikowski <mateusz.kulikowski@gmail.com>

obj-y	+= dragonboard410c.o
obj-y	+= misc.o

# HACK: yell that this makefile has been called
$(warning "dragonboard410c/Makefile has been called")