name: Build images

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: sm7125-xiaomi-miatoll
          #- device: sm7125-xiaomi-curtana

    name: Build ${{ matrix.device }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: next

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends gcc-aarch64-linux-gnu libgnutls28-dev

      # mkbootimg in Ubuntu repos is broken, so use the forked C variant
      - name: Build mkbootimg
        run: |
          git clone https://github.com/osm0sis/mkbootimg --depth=1
          cd mkbootimg
          CFLAGS=-Wstringop-overflow=0 make mkbootimg
          cd ..

      - name: Configure U-Boot
        run: |
          make ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- O=.output qcom_defconfig qcom-phone.config qcom-sm71xx.config qcom-multi-dtb.config

      - name: Build U-Boot
        run: |
          make ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- O=.output -j$(nproc)

      - name: Assemble Android boot.img
        run: |
          ./mkbootimg/mkbootimg --base 0x0 --kernel_offset 0x8000 --pagesize 4096 --kernel .output/u-boot-fit-dtb.bin --ramdisk .output/fit-dtb.blob --ramdisk_offset 0x1000000 --dtb .output/dts/upstream/src/arm64/qcom/qcom-multi-dummy.dtb --dtb_offset 0x1f00000 --header_version 2 --second_offset 0x0 -o .output/u-boot.img

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: u-boot-${{ matrix.device }}.img
          path: .output/u-boot.img

